#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

if [[ -s "$HOME/.dotfiles/aliases.sh" ]]; then
  source "$HOME/.dotfiles/aliases.sh"
fi

if [[ -s "$HOME/.nvm/nvm.sh" ]]; then
  source ~/.nvm/nvm.sh
fi

if [[ -s "$HOME/go/current" ]]; then
  export GOROOT="$HOME/go"
  export PATH="$PATH:$GOROOT/bin"
fi
if [[ -s "$HOME/Projects/go" ]]; then
  export $GOPATH="$HOME/Projects/go"
fi

